### ISSUE TITLE
raven and Django 1.10

### ISSUE THREAD

**Issue by AnSharipov** [getsentry/raven-python#826] opened 2016-08-08 17:36 UTC
Cant get reports from raven on Django 1.10

My configurations in **settings.py**

```
INSTALLED_APPS = [
    'raven.contrib.django.raven_compat'
]

import raven
RAVEN_CONFIG = {
    'dsn': 'https://*********CODE**********@app.getsentry.com/90733',
    # If you are using git, you can also automatically configure the
    # release based on the git info.
    # 'release': raven.fetch_git_sha(os.path.dirname(__file__)),
}
```

**Comment by dcramer** [comment] 2016-08-08 17:42
@AnSharipov are you using the latest version of the SDK?

**Comment by AnSharipov** [comment] 2016-08-08 17:51
@dcramer yes, I updated raven

**Comment by dcramer** [comment] 2016-08-08 18:39
I committed an example Django 1.10 project which is unable to reproduce this failure.

Have you tried manually sending an event?

**Comment by dcramer** [comment] 2016-08-08 18:42
https://app.getsentry.com/share/issue/313235342e313438333232363935/

**Comment by dcramer** [comment] 2016-08-08 22:04
Also 5.24.3 fixes the 'raven test' command.

Closing this as I need more info to reproduce.

**Closed by dcramer** 2016-08-08 22:04 UTC
