### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by pehrlich** [getsentry/raven-python#604] opened 2015-04-29 01:59 UTC
Recently started getting the follow error, without any explicit change to Raven or Sentry configuration.  Google results are unrevealing.  Is there something known that can cause this?  

Any proper ways of logging more fully the original `AttributeError`, which caused the Sentry error, besides disabling Sentry?

``` bash
INFO:werkzeug:172.17.42.1 - - [29/Apr/2015 01:02:51] "POST / HTTP/1.1" 500 -
ERROR:sentry.errors:Unable to reach Sentry log server: HTTP Error 413: Request Entity Too Large (url: https://app.getsentry.com/api/39671/store/, body: b'<html>\r\n<head><title>413 Request Entity Too Large</title></head>\r\n<body bgcolor="white">\r\n<center><h1>413 Request Entity Too Large</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n')
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/raven/transport/threaded.py", line 159, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/usr/local/lib/python3.4/site-packages/raven/transport/http.py", line 49, in send
    ca_certs=self.ca_certs,
  File "/usr/local/lib/python3.4/site-packages/raven/utils/http.py", line 62, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 413: Request Entity Too Large
ERROR:sentry.errors:Failed to submit message: "AttributeError: 'dict' object has no attribute 'encode'"
```

**Comment by dcramer** [comment] 2015-04-29 02:09
Is this getsentry.com or are you hosting it yourself?

**Comment by pehrlich** [comment] 2015-04-29 03:03
Getsentry.com

**Comment by dcramer** [comment] 2015-04-29 06:50
This would mean the packet is *very* large. I think we should do something on our end around logging, but it's a little complicated. We definitely should log a reasonable version of the message (beyond just what we give you here). Unfortunately without changes to the client I don't have a great answer.

**Comment by pehrlich** [comment] 2015-04-29 07:03
Hm, ok. What composes the packet? I am working with a number large files,
perhaps one is getting itself attached to the error report somehow, and we
definetly wouldn't want or need that.

Happy to test out or make changes as advised.

**Comment by dcramer** [comment] 2015-04-30 19:50
Closing this out as it was (potentially) resolved elsewhere

**Comment by pehrlich** [comment] 2015-04-30 19:54
nice, thank you

**Comment by jmagnusson** [comment] 2015-08-27 09:56
It was? I'm still experiencing 413 responses from getsentry.com when POSTing a 5.3MB payload.
Perhaps you could log something in Sentry when this happens so one knows an error occurred. Took some digging in syslogs to find the error.

**Comment by dcramer** [comment] 2015-08-27 17:48
@jmagnusson do you see this in the 5.6 release?

**Comment by jmagnusson** [comment] 2015-08-28 06:35
Yup, still. `Sentry responded with an error: HTTP Error 413: Request Entity Too Large (url: https://app.getsentry.com/api/.../store/)`

**Comment by pehrlich** [comment] 2015-09-23 19:30
So this is still an issue, although thanks to your help earlier/elsewhere, it is being logged sufficiently locally.  

A believe a couple actions should be taken:
 - Upon receiving a too large entity, the server should log a proxy exception, alerting the user that an event happened which was un-capturable.  This would prevent silent doom.
 - An API should be devised to all the automatic or selective truncation of large strings when errors are thrown.  E.g., if I have an attribute error on a dictionary with a large string key, in many cases I don't have any need to know the contents of that key, beyond perhaps the first 100 chars to indicate its further contents.

**Comment by jhubert** [comment] 2016-03-09 06:29
Seeing this as well from the error dump of a complex elasticsearch query.

**Comment by jmagnusson** [comment] 2016-03-09 09:01
It still hasn't been resolved?

**Comment by ruimarinho** [comment] 2016-04-11 10:34
Just got hit by this issue (not related to the python lib though). What's the maximum body size allowed by sentry?

**Comment by dcramer** [comment] 2016-04-11 16:32
Most of the time this is due to the configuration of the server. If this is getsentry.com the request limit is *extremely* high and there's no way you should be hitting it. If you are, then it likely means that the client side variable trimming isn't working correctly, or has been re-configured to send data that is too large.

**Comment by ruimarinho** [comment] 2016-04-11 22:42
This is getsentry.com and the issue is that the metadata I've submitted is simply too large and not due to an error in trimming (it exceeds 1Mb). @pehrlich mentioned that the sentry server could log an exception whenever a request that contains a large body is discarded, but that would require processing the whole message to find out the id which would defeat the original protection in place - unless, of course, the id can be obtained in another way (query parameter?) while still discarding an offending body.

The second @pehrlich's suggestion is inline we something that I wanted to suggest too - let the client preemptively calculate the body size and remove certain information (e.g. all metadata?) so that at least the most relevant pieces still won't go unnoticed.

**Comment by evdoks** [comment] 2016-06-24 13:27
Any news here? We are still getting this error 413 with getsentry.com.

**Comment by jakubzitny** [comment] 2016-06-27 11:18
We were having the same problem on self-hosted sentry. Of course, the problem was in request size limit in Nginx.

**Comment by joar** [comment] 2016-10-05 07:42
We are experiencing this issue with `raven==5.36.0`, using `raven.transport.http.HTTPTransport`, on sentry.io.

**Comment by jmagnusson** [comment] 2017-10-06 09:09
Still getting request entity too large:

```
2017-10-06 04:02:45,810|sentry.errors|ERROR|Sentry responded with an error: HTTP Error 413: Request Entity Too Large (url: https://sentry.io/api/<id>/store/) (base.py:682)
```

Any chance this could get prioritized? I'm missing exceptions from some of our most important endpoints because of it.

**Comment by mitsuhiko** [comment] 2017-10-06 17:46
I think we will need to do some better pruning for the breadcrumbs which I assume are triggering this in the case mentioned above.

**Comment by jmagnusson** [comment] 2017-11-02 16:03
@mitsuhiko Any hints as to when this might be fixed?

**Comment by mitsuhiko** [comment] 2017-11-02 18:29
I'm going to take a look at this.

**Comment by geuben** [comment] 2017-11-21 21:42
I am also experiencing this issue. The excessive size in my case is certainly coming from the breadcrumbs

**Comment by philtrep** [comment] 2017-12-06 20:24
@mitsuhiko any update on status? 😄

**Comment by mitsuhiko** [comment] 2017-12-06 21:07
@philpep i looked at this a few days back but we do not record an excessive amounts of crumbs by default. Any ideas what could be logged in your case?

**Comment by mitsuhiko** [comment] 2017-12-06 21:07
(that would be sql queries etc. Just want to get an idea where to trim here)

**Comment by fcoury** [comment] 2017-12-07 15:59
I am running into the same issue on a React/Redux app:

`Content-Length:183107`

Is 183kb considred too large?

**Comment by philtrep** [comment] 2017-12-07 16:17
@fcoury The limit seems to be 100kb https://docs.sentry.io/learn/quotas/#attributes-limits

@mitsuhiko mistag 😉  Currently investigating, should have more info later today or tomorrow.

**Comment by notatestuser** [comment] 2017-12-18 04:13
Having a request that is around 111KB dropped by `sentry.io/api`. That limit seems a little low - we simply log all of our redux actions and send them as breadcrumbs.

**Comment by whisller** [comment] 2018-01-03 10:31
Experiencing same problem with `raven==6.1.0` + `raven-python-lambda==0.1.4`.
```
Sentry responded with an error: HTTP Error 413: Request Entity Too Large (url: https://sentry.io/api/211040/store/)
```

**Comment by peterbe** [comment] 2018-01-25 20:13
I have `raven==0.6.4` and Django 1.17. Saw these errors in my uwsgi log too. No idea what to do about it. 
I injected a little logging into the `lib/python3.5/site-packages/raven/utils/http.py` just to get an insight into what that data is. I still don't know what it is other than it's some binary blob. It's size hovers around 100KB.
I'm using sentry.io.

**Comment by jmagnusson** [comment] 2018-02-01 20:31
This issue almost 3 years old now. Will it ever be fixed?

I've always loved Sentry and felt confident in that it will notify us of any exceptions that occur in production, but this issue scuffs that feeling a bit.

**Comment by dcramer** [comment] 2018-02-01 20:32
@jmagnusson it should be very rare you'd see this, and might be more commonly happening with on-premise installs since max size is configurable. If you're seeing it on sentry.io let us know and we can probably just duct tape packet size in the mean time.

**Comment by jmagnusson** [comment] 2018-02-01 20:33
@dcramer We're using your hosted solution

**Comment by peterbe** [comment] 2018-02-01 20:59
@dcramer I'm using sentry.io and I'm getting it too.

**Comment by dcramer** [comment] 2018-02-01 22:08
@jmagnusson @peterbe are you still experiencing this?

**Comment by peterbe** [comment] 2018-02-02 13:35
> are you still experiencing this? 

As of 8 days ago I was. See my previous comment. 
I can provide you more details but in private in case I do something silly that reveals too much.

**Comment by dcramer** [comment] 2018-02-02 16:44
I meant as in right now. We made changes yesterday which should have reduced the impact.

**Comment by peterbe** [comment] 2018-02-02 20:00
@dcramer Yes, but because I don't know how to corner this, here's what I did:
(Note: I'm doing this on a side-project so attention is restricted)

I injected some print in `site-packages/raven/utils/http.py` towards the end:
```diff
-   return opener.open(url, data, timeout)
+   try:
+        return opener.open(url, data, timeout)
+   except Exception:
+        print("EXCEPTION!!!!", url, url.get_full_url(), data[:1000])
+        raise
```
Then I hawkishly watch my uwsgi log file and I get this:
```
EXCEPTION!!!! <urllib.request.Request object at 0x7fd9103efb38> https://sentry.io/api/196160/store/ b'x\x9c\xec\xbdiw\xe2H\xb20\xfcW\xd4\xf5~p\xd5)\x97\xd9\xb7\xea;\xb7\x0f\x8b0xe\xf3\x82\xa7\xe6\xf4MP"\xc9\x08\t$
Sentry responded with an error: HTTP Error 413: Request Entity Too Large (url: https://sentry.io/api/196160/store/)
Traceback (most recent call last):
  File "/var/lib/django/songsearch/venv/lib/python3.5/site-packages/raven/transport/threaded.py", line 165, in send_sync
    super(ThreadedHTTPTransport, self).send(url, data, headers)
  File "/var/lib/django/songsearch/venv/lib/python3.5/site-packages/raven/transport/http.py", line 43, in send
    ca_certs=self.ca_certs,
  File "/var/lib/django/songsearch/venv/lib/python3.5/site-packages/raven/utils/http.py", line 67, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 413: Request Entity Too Large
['OSError: write error']
```

**Comment by dcramer** [comment] 2018-02-02 20:07
@peterbe any chance you could try to capture data to a file and email that to david at sentry.io?

**Comment by dcramer** [comment] 2018-02-02 20:08
Aside, you can sign with PGP key if you're concerned: https://sentry.io/security/

**Comment by peterbe** [comment] 2018-02-02 20:21
@dcramer I don't think it needs to be signed up I've written a little hack now to generate these data files. I'll email you one if I get another exception. At the time of writing I haven't had one happen in a while.

**Comment by dcramer** [comment] 2018-02-02 20:39
The problem in this specific example is breadcrumbs are not truncating log messages. In this case theres an elasticsearch logger (not sure if yours or the official library), and an unbelievably large debug message which seems to be the full payload being inserted.

**Comment by peterbe** [comment] 2018-02-02 21:12
Stock Django 1.11 with no fancy logging specifically for elasticsearch_dsl. I appreciate that sometimes Elasticsearch barfs but there should still be an error sent to Sentry. I do use this little snippet for calling elasticsearch_dsl:

```python
from elasticsearch.exceptions import (
    ConnectionTimeout,
    ConnectionError,
    TransportError,
    NotFoundError,
)

_es_operational_exceptions = (
    ConnectionTimeout,
    ConnectionError,
    TransportError,
)


def es_retry(callable, *args, **kwargs):
    sleep_time = kwargs.pop('_sleep_time', 1)
    attempts = kwargs.pop('_attempts', 10)
    verbose = kwargs.pop('_verbose', False)
    try:
        return callable(*args, **kwargs)
    except _es_operational_exceptions as exception:
        if attempts:
            attempts -= 1
            if verbose:
                print("ES Retrying ({} {}) {}".format(
                    attempts,
                    sleep_time,
                    exception
                ))
            time.sleep(sleep_time)
        else:
            raise
```

I don't see those `ES Retrying ` prints in the uwsgi logs.

**Comment by dcramer** [comment] 2018-02-02 23:29
@peterbe sorry I should have been clear that i was intending to fix it, but the behavior is poor in general.

**Closed** 2018-02-03 03:44 UTC
Labels: Breadcrumbs, Bug, Critical

**Comment by d-dorazio** [comment] 2018-02-09 10:29
any chance of deploying a new version of `raven` which includes the fix? This issue has been a real pain for a long time for us and we really want to try this fix.

**Comment by ashwoods** [comment] 2018-02-09 20:33
@d-dorazio will be out by tomorrow.

**Comment by ryechus** [comment] 2020-05-05 22:26
I am still experiencing this issue even after updating to version 6.10.0.

**Comment by davidpaley** [comment] 2020-08-04 20:20
I am having this error working with next.js and "@sentry/react": version 5.20.1 with the default configuration of React

**Comment by Empact** [comment] 2020-11-06 05:47
Anyone having this issue, who thinks it might come down to breadcrumbs, you can set the `maxBreadcrumbs` init setting (default and max value: 100) to reduce the number of breadcrumbs conveyed.

https://github.com/getsentry/sentry-javascript/blob/7c142839036e77161a6f707196762eb718b723cc/packages/types/src/options.ts#L70-L74

Note the code comment is incorrect about the default being 30:

https://github.com/getsentry/sentry-javascript/blob/bd6028a9f0cfb00c79e46fd5b99ef2b442474bac/packages/hub/src/hub.ts#L38-L48

**Comment by Empact** [comment] 2020-11-06 05:55
For reference, @davidpaley apparently solved his problem here: https://github.com/getsentry/sentry-javascript/issues/2798
