### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'rule'

### ISSUE THREAD

**Issue by asiekkowa** [getsentry/raven-python#865] opened 2016-09-19 14:37 UTC
(I use python 3.5 and flask.) I made update the raven package today. From this time I had below errors:
```
File "raven/contrib/flask.py", line 235, in after_request                
    self.client.transaction.pop(request.url_rule.rule)                                                                        
AttributeError: 'NoneType' object has no attribute 'rule'    
```
and
```
raven/contrib/flask.py", line 220, in before_request                │
self.client.transaction.push(request.url_rule.rule)                              
AttributeError: 'NoneType' object has no attribute 'rule'  
```

**Comment by mattrobenolt** [comment] 2016-09-19 14:39
This looks to be a duplicate of https://github.com/getsentry/raven-python/issues/863

**Closed by mattrobenolt** 2016-09-19 14:39 UTC
