### ISSUE TITLE
`Client.captureException(None)` results in a `UnicodeDecodeError` with python 2.7 if future library is used

### ISSUE THREAD

**Issue by rwarren** [getsentry/raven-python#803] opened 2016-07-16 21:23 UTC
This is happening on python 2.7.9 with raven 5.23.0.  Full traceback from the sending thread is below:

```
Traceback (most recent call last):
  File "/home/russ/.virtualenvs/edms/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "/home/russ/.virtualenvs/edms/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "/home/russ/.virtualenvs/edms/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "/home/russ/.virtualenvs/edms/lib/python2.7/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/russ/.virtualenvs/edms/lib/python2.7/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/russ/.virtualenvs/edms/lib/python2.7/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/home/russ/.virtualenvs/edms/lib/python2.7/site-packages/raven/utils/http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "/home/russ/.virtualenvs/edms/lib/python2.7/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/opt/python2.7.9/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/opt/python2.7.9/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/opt/python2.7.9/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/opt/python2.7.9/lib/python2.7/httplib.py", line 848, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
```

Note the `future` module in there... suspicious?

For the failed capture, here is some debug info on what is being sent to the raven Client's `transport.async_send`:

```
>>> type(data), data[:10], headers
(<type 'str'>,
 'x\x9c\xed]\x0bw\xe2F\xb2\xfe',
 {'Content-Encoding': 'deflate',
  'Content-Type': 'application/octet-stream',
  'User-Agent': 'raven-python/5.23.0',
  'X-Sentry-Auth': 'Sentry sentry_timestamp=1468702548.44, sentry_client=raven-python/5.23.0, sentry_version=6, sentry_key=3de74049829c4e22827b100a5ece12e1, sentry_secret=<too secret to include>'})
```

At the `httplib` exception location (`msg += message_body`) in the thread, we end up with `str` and `unicode`, and the zlib-compressed str block:

```
>>> type(msg), type(message_body), message_body[:10]
(<type 'unicode'>, <type 'str'>, 'x\x9c\xed]\x0bw\xe2F\xb2\xfe')
```

Also potentially of note is that `self._buffer` that got joined prior to the exception line was a mixed bag of `str` and `unicode`:

```
>>> map(type, self._buffer)
[<type 'unicode'>,
 <type 'str'>,
 <type 'unicode'>,
 <type 'str'>,
 <type 'unicode'>,
 <type 'str'>,
 <type 'str'>,
 <type 'unicode'>,
 <type 'str'>]
>>> self._buffer[:3]
[u'POST /api/4/store/ HTTP/1.1',
 'Accept-Encoding: identity',
 u'Content-Length: 5476']
```

**Comment by dcramer** [comment] 2016-07-19 05:11
@rwarren i dont suppose you're able to get the full body? or alternatively a smaller test case? it's possible this is related to breadcrumbs, but at the very least the unicode vs string header (albeit odd) shouldn't be an issue.

**Comment by mitsuhiko** [comment] 2016-07-19 14:18
What is this "future backports" thing?

**Comment by rwarren** [comment] 2016-07-19 14:19
Unfortunately I can't seem to produce a small test case yet, although I spent some time at it.  Building up from nothing I can't get it to fail.  Reducing from the larger case is much harder.

As for the full message body, I'm not 100% sure where you mean (since at that httlib location *any* `message_body` with char `0x9C` in it will fail.  Hopefully the below helps without being too obtuse? Can't really post the full traceback.

The last raven line of code that is sending the request is [this one](https://github.com/getsentry/raven-python/blob/master/raven/utils/http.py#L46):

    return self.do_open(ValidHTTPSConnection, req)

Your `req` there is supposed to be a `urllib.request.Request` instance, but in our case ends up as an instance of `future.backports.urllib.request.Request`).

The snipped `req.headers` dict is below, with all keys+values being `str`, not `unicode`:
```
{'Content-encoding': 'deflate',
 'Content-type': 'application/octet-stream',
 'User-agent': 'raven-python/5.23.0',
 'X-sentry-auth': 'Sentry sentry_timestamp=1468935944.59, sentry_client=raven-python/5.23.0, sentry_version=6, sentry_key=<snip>, sentry_secret=<snip>'}
```

The `req.data` is a `str` which is a `zlib.compress`ed `dict`.  Decompressing that to the source dict (and snipping the long traceback), it is below:
```
{u'culprit': u'ImpRpcLib in _handle_RPC_FAULT',
 u'event_id': u'5a02bd3dcbca40a999e656833e6f5030',
 u'exception': {u'values': [{u'module': u'ImpRpcLib',
                             u'stacktrace': '<snipped>',
                             u'type': u'Fault',
                             u'value': u'<ERR_InternalError> -- Internal error: (ProgrammingError) syntax error at or near "ASELECT"\nLINE 4: ASELECT 1\n        ^\n \'\\n-- Master FCT query view\\n\\nASELECT 1\' {}.  Fault data = u\'(ProgrammingError) syntax error at or near "ASELECT"\\nLINE 4: ASELECT 1\\n        ^\\n\''}]},
 u'extra': {u'sys.argv': [u"'EDMS'", u"'-nograb'"]},
 u'level': 40,
 u'message': u'Fault: <ERR_InternalError> -- Internal error: (ProgrammingError) syntax error at or near "ASELECT"\nLINE 4: ASELECT 1\n        ^\n \'\\n-- Master FCT query view\\n\\nASELECT 1\' {}.  Fault data = u\'(ProgrammingError) syntax error at or near "ASELECT"\\nLINE 4: ASELECT 1\\n        ^\\n\'',
 u'modules': {u'python': u'2.7.9'},
 u'platform': u'python',
 u'project': u'4',
 u'sdk': {u'name': u'raven-python', u'version': u'5.23.0'},
 u'server_name': u'beast',
 u'tags': {},
 u'time_spent': None,
 u'timestamp': u'2016-07-19T13:45:44Z'}
```
One other thing: Since you mentioned breadcrumbs, we do actually have to make the client with `install_logging_hook = False` due to a breadcrumbs failure that happens in our environment.  However, small test cases with this in place don't cause the failure.  Not sure if that helps or not.

**Comment by mitsuhiko** [comment] 2016-07-19 14:19
My assumption is that you have something that monkeypatches around in Python's internals. We are not using this, i'm surprised it ends up in the stacktrace.

**Comment by rwarren** [comment] 2016-07-19 14:29
@mitsuhiko It's this thing: https://github.com/PythonCharmers/python-future

This is what I was referring to when I said:
> Note the future module in there... suspicious?

However, a simple test case like below works perfectly fine, so it *seems* like it isn't just the monkeypatching.
```python
import raven
from future import standard_library   #haaaack
from sentry_urls import TEST_URL1
c = raven.Client(TEST_URL1,
                 install_logging_hook=False)
try:
    1/0
except Exception as e:
    capture_exception(e)
    import time
    time.sleep(5) # to ensure the sentry thread does its thing before dying
```

**Comment by mitsuhiko** [comment] 2016-07-19 14:36
@rwarren most likely what happens is that future has a bug where it starts to unicodeize something that is not supposed to be unicode in python 2 and it fails once binary data (like zlib encoded data) is being sent through urllib.

Not sure what we can do here. This very much looks like a bug in future.

**Comment by mitsuhiko** [comment] 2016-07-19 14:39
The only thing we can do in this situation is detect that the urllib was modified and raise a runtime error. Not sure how we can deal with this otherwise.

**Comment by rwarren** [comment] 2016-07-19 14:47
Ok.  Thanks.  I'll see fiddle some more and see what I can do, or try and isolate the problem to report back to the future project. Or ditch it.

Not sure that raising an error when you see patched urllib is a great idea. 

Always a pleasure with unicode.

**Comment by mitsuhiko** [comment] 2016-07-19 14:47
@rwarren the problem is not so much unicode but code that changes unicode behavior :)

**Comment by Siecje** [comment] 2016-09-12 19:06
You have to call ```standard_library.install_aliases()```

```Python
import raven
from future import standard_library   #haaaack
standard_library.install_aliases() # new
from sentry_urls import TEST_URL1
c = raven.Client(TEST_URL1,
                 install_logging_hook=False)
try:
    1/0
except Exception as e:
    c.captureException()
    import time
    time.sleep(5) # to ensure the sentry thread does its thing before dying
```

**Comment by Siecje** [comment] 2016-09-12 19:47
This [line](https://github.com/python/cpython/blob/2.7/Lib/httplib.py#L895) fails.

```Python
if isinstance(message_body, str):
            msg += message_body # here
```

 because ```self_buffer``` contains both ```unicode``` and ```str```.

```Python
>>> self._buffer
[u'POST /api/6/store/ HTTP/1.1',
 'Accept-Encoding: identity',
 u'Content-Length: 828',
 'Content-Encoding: deflate',
 u'Connection: close',
 'X-Sentry-Auth: Sentry sentry_timestamp=1473708698.35, sentry_client=raven-python/5.26.0, sentry_version=6, sentry_key=********************************, sentry_secret=********************************',
 'User-Agent: raven-python/5.26.0',
 u'Host: sentry.domain.com',
 'Content-Type: application/octet-stream',
 '',
 '']
```


And ```message_body``` contains bytes that can't be expressed in ```unicode```?

```message_body
'x\x9c\xadUm\x8b\xdc6\x10\xfe+\xc2\xf9\xe0;\xc8\xfa\xfdm\x97\xb4\xb4\xcd] .... '
```

The reason ```self._buffer``` contains both ```str``` and ```unicode``` is that with ```future``` urllib2 properties are ```unicode```. 

For example [here](https://github.com/getsentry/raven-python/blob/6913e97b4c350f12a400b5acda030e84b5b1c572/raven/utils/http.py#L46)

```Python
    class ValidHTTPSHandler(urllib2.HTTPSHandler):
        def https_open(self, req):
            return self.do_open(ValidHTTPSConnection, req) #here
```

```req.host``` is ```u'sentry.domain.com'```

**Comment by hyperair** [comment] 2019-07-23 04:31
Seems to be solved as of https://github.com/getsentry/raven-python/commit/c69abaa1506a426802e979c7f8c6a4ab0ef9c4d7#diff-1009f02b22291a2682b3d868a2211291R190

Specifically, this commit makes it so that `raven.utils.compat.urllib2` is no longer `future.backports.urllib.request` on Python 2.

**Comment by untitaker** [comment] 2019-08-08 10:07
closing, thanks!

**Closed by untitaker** 2019-08-08 10:07 UTC
