### ISSUE TITLE
Raven + Celery 4.1.0 not reporting task failures

### ISSUE THREAD

**Issue by hartror** [getsentry/raven-python#1100] opened 2017-10-02 08:59 UTC
Environment:

OS X 10.11.6
Python 2.7.13
rabbitmq 3.6.1
celery 4.1.0 (works with 3.1.23)
raven 6.2.1

**Code:**

```
import celery

# Sentry
client = Client(SENTRY_DSN)
register_logger_signal(client)
register_signal(client)

# Celery
celery_app = celery.Celery()

@celery_app.task(name='test')
def test():
    1 / 0
```

**Commands:**

Run worker: `celery worker -A sentry_case.celery_app -l INFO -c 1`
and then submit a task: `celery call -A sentry_case.celery_app test`

**Additional information:**

Raven was partially working because this exception made it through to Sentry:

```
KeyError: u'test'
  File "celery/worker/consumer/consumer.py", line 561, in on_task_received
    strategy = strategies[type_]
```

ps. Thanks for an amazing product!

**Comment by ashwoods** [comment] 2017-10-13 13:26
@hartror thx for the report, but I am having a hard time to reproduce:
I used docker based rabbitmq 3.6.1 and latest, and redis, with your setup:
https://github.com/ashwoods/raven-celery-testcase

current pip freeze:
amqp==2.2.2
billiard==3.5.0.3
celery==4.1.0
contextlib2==0.5.5
kombu==4.1.0
pytz==2017.2
raven==6.2.1
vine==1.1.4

Can you try running it from raven-celery-testcase from a fresh virtualenv to rule out any funky celery naming issues?

**Comment by ashwoods** [comment] 2017-11-10 14:36
Closing this as I can't reproduce.

**Closed by ashwoods** 2017-11-10 14:36 UTC
Labels: Integrations: Celery, Need more information
