### ISSUE TITLE
Django 2.0 compatibility

### ISSUE THREAD

**Issue by Mogost** [getsentry/raven-python#1159] opened 2017-12-11 10:03 UTC
```
Traceback (most recent call last):
  File "/***//lib/python3.5/site-packages/raven/contrib/django/middleware/__init__.py", line 101, in process_view
    client.get_transaction_from_request(request)
  File "/***//lib/python3.5/site-packages/raven/contrib/django/client.py", line 309, in get_transaction_from_request
    return self.resolver.resolve(request.path)
  File "/***//lib/python3.5/site-packages/raven/contrib/django/resolver.py", line 88, in resolve
    match = self._resolve(resolver, path)
  File "/***//lib/python3.5/site-packages/raven/contrib/django/resolver.py", line 53, in _resolve
    match = resolver.regex.search(path)
AttributeError: 'URLResolver' object has no attribute 'regex'
```

**Comment by cryporchild** [comment] 2017-12-11 10:07
This is a duplicate of #1127.

**Comment by Mogost** [comment] 2017-12-11 10:07
Sorry, I see that is already fixed in https://github.com/getsentry/raven-python/commit/844a7cb78c5b7356f37bfd758e596c7a13d9fb67 .
Waiting for a new release.

**Closed** 2017-12-11 10:08 UTC
