### ISSUE TITLE
In Django, "Unknown command: 'raven'"

### ISSUE THREAD

**Issue by glarrain** [getsentry/raven-python#359] opened 2013-09-16 16:13 UTC
According to http://raven.readthedocs.org/en/latest/config/django.html, "Once you’ve configured the client, you can test it using the standard Django management interface". This was added in fb4181433d3613c647f288d364a5697eae7152e9.

With Raven 3.4.1 and Django 1.4.8:
```
$ python manage.py raven test
Unknown command: 'raven'
Type 'manage.py help' for usage.
```

**Comment by xordoquy** [comment] 2015-02-12 09:26
I'm closing this because I haven't been able to reproduce it. I'd be happy whenever someone can setup up an environment where this happens and which I can investigate.

**Closed by xordoquy** 2015-02-12 09:26 UTC

**Comment by chris-erickson** [comment] 2016-03-18 17:52
I'm having a similar problem right now.  At this point, it seems to be an issue with the DSN not being set, but as far I know right now, it's not a raven issue - setting up raven depends on a `dsn` var being set.  I use `django-getenv`to load vars like: `dsn = env("RAVEN_DSN", None)` and in my case, dsn isn't set.  I haven't figured out why yet.

**Comment by chris-erickson** [comment] 2016-06-14 13:37
I eventually found the problem, and it had to do with the git commit integration.  Originally, I was using:

```python
'release': raven.fetch_git_sha(os.path.dirname(__file__)),
```
which worked for months.  It was unable to find a git repo at that location any longer.  It doesn't exist at the same directory as `settings.py` but git commands used to (and should) work anywhere below the git repo directory.  To resolve this, I just changed to:

```python
'release': raven.fetch_git_sha(DJANGO_ROOT),
```
and we're back in business.

**Comment by ACPK** [comment] 2017-06-15 22:49
Also having this issue.
