### ISSUE TITLE
Crash on manage.py raven test --data foo

### ISSUE THREAD

**Issue by jleclanche** [getsentry/raven-python#1098] opened 2017-10-01 20:42 UTC
I was debugging some unrelated issue and ended up with this:

```pytb
[20:40:13] admin@ ~ % python manage.py raven test --data foo 
Traceback (most recent call last):
  File "/.../source/manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/.../env/lib/python3.4/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/.../env/lib/python3.4/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/.../env/lib/python3.4/site-packages/django/core/management/base.py", line 277, in run_from_argv
    options = parser.parse_args(argv[2:])
  File "/.../env/lib/python3.4/site-packages/django/core/management/base.py", line 58, in parse_args
    return super(CommandParser, self).parse_args(args, namespace)
  File "/usr/lib/python3.4/argparse.py", line 1730, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.4/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.4/argparse.py", line 1968, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.4/argparse.py", line 1908, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.4/argparse.py", line 1836, in take_action
    action(self, namespace, argument_values, option_string)
  File "/.../env/lib/python3.4/site-packages/raven/contrib/django/management/commands/raven.py", line 24, in __call__
    setattr(namespace, self.dest, store_json(values[0]))
TypeError: store_json() missing 3 required positional arguments: 'opt_str', 'value', and 'parser'
```

That doesn't look right. Although I'm not sure if --data is still even supported.

**Comment by ashwoods** [comment] 2017-10-02 09:40
I think this is a duplicate of #1078 and fixed in master.

**Comment by jleclanche** [comment] 2017-10-02 14:38
looks like it

**Closed** 2017-10-28 19:05 UTC
